import {cp,readdir,writeFile,rm} from 'node:fs/promises';
import {resolve} from 'node:path';
// Keep GitHub Pages' existing main/root publishing mode. Commit generated pages
// with each source change; .nojekyll allows the generated _astro directory.
const root=resolve(import.meta.dirname,'..');
// This directory contains only assets generated by this build.
await rm(resolve(root,'_astro'),{recursive:true,force:true});
for(const file of await readdir(resolve(root,'.build'))){
 if(file.endsWith('.html') || file==='_astro') await cp(resolve(root,'.build',file),resolve(root,file),{recursive:true});
}
await writeFile(resolve(root,'.nojekyll'),'');
// Preserve legacy course URLs and assets in local production previews as well.
for(const folder of ['courses','assets'])await cp(resolve(root,folder),resolve(root,'.build',folder),{recursive:true,filter:source=>!source.endsWith('.DS_Store')});
console.log('Static pages published to repository root; legacy course URLs preserved.');
